
import type { AnalysisResult, CommunityOutbreak, StoreProduct, StoreLocation } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/600/400`;
const getImageHint = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageHint || 'placeholder';

export const mockHistory: AnalysisResult[] = [
  {
    id: 'case_001',
    timestamp: '2024-07-20T10:30:00Z',
    image: getImage('tomato_late_blight_leaf'),
    imageHint: getImageHint('tomato_late_blight_leaf'),
    crop: 'Tomato',
    predictions: [
      { label: 'Tomato Late Blight', confidence: 0.92 },
      { label: 'Tomato Early Blight', confidence: 0.05 },
      { label: 'Healthy', confidence: 0.03 },
    ],
    severity: { percentage: 45, band: 'Medium' },
    gradCamImage: getImage('tomato_late_blight_cam'),
    risk: { score: 0.75, explanation: 'High humidity and recent detections increase risk.' },
    status: 'Completed',
  },
  {
    id: 'case_002',
    timestamp: '2024-07-20T09:15:00Z',
    image: getImage('maize_common_rust_leaf'),
    imageHint: getImageHint('maize_common_rust_leaf'),
    crop: 'Maize',
    predictions: [
      { label: 'Maize Common Rust', confidence: 0.61 },
      { label: 'Maize Gray Leaf Spot', confidence: 0.25 },
      { label: 'Healthy', confidence: 0.14 },
    ],
    severity: { percentage: 15, band: 'Low' },
    gradCamImage: getImage('maize_common_rust_cam'),
    risk: { score: 0.45, explanation: 'Moderate risk due to stable weather conditions.' },
    status: 'Pending Review',
  },
  {
    id: 'case_003',
    timestamp: '2024-07-19T17:00:00Z',
    image: getImage('potato_early_blight_leaf'),
    imageHint: getImageHint('potato_early_blight_leaf'),
    crop: 'Potato',
    predictions: [
      { label: 'Potato Early Blight', confidence: 0.98 },
      { label: 'Healthy', confidence: 0.01 },
      { label: 'Potato Late Blight', confidence: 0.01 },
    ],
    severity: { percentage: 25, band: 'Medium' },
    gradCamImage: getImage('potato_early_blight_cam'),
    risk: { score: 0.60, explanation: 'Increased detections in the area.' },
    status: 'Completed',
  },
  {
    id: 'case_004',
    timestamp: '2024-07-18T11:45:00Z',
    image: getImage('healthy_tomato_leaf'),
    imageHint: getImageHint('healthy_tomato_leaf'),
    crop: 'Tomato',
    predictions: [
      { label: 'Healthy', confidence: 0.99 },
      { label: 'Tomato Late Blight', confidence: 0.01 },
      { label: 'Tomato Early Blight', confidence: 0.00 },
    ],
    severity: { percentage: 2, band: 'Low' },
    gradCamImage: getImage('healthy_tomato_cam'),
    risk: { score: 0.15, explanation: 'Low risk, plant appears healthy.' },
    status: 'Completed',
  },
    {
    id: 'case_005',
    timestamp: '2024-07-17T14:20:00Z',
    image: getImage('potato_late_blight_leaf_2'),
    imageHint: getImageHint('potato_late_blight_leaf_2'),
    crop: 'Potato',
    predictions: [
      { label: 'Potato Late Blight', confidence: 0.55 },
      { label: 'Potato Early Blight', confidence: 0.40 },
      { label: 'Healthy', confidence: 0.05 },
    ],
    severity: { percentage: 65, band: 'High' },
    gradCamImage: getImage('potato_late_blight_cam_2'),
    risk: { score: 0.85, explanation: 'High severity and favorable weather for blight spread.' },
    status: 'Pending Review',
  },
];

export const reviewQueue = mockHistory.filter(item => item.status === 'Pending Review');


export const communityOutbreaks: CommunityOutbreak[] = [
    {
        id: 'outbreak_01',
        disease: 'Wheat Brown Rust',
        crop: 'Wheat',
        location: 'Karnal, Haryana',
        latitude: 29.6857,
        longitude: 76.9905,
        detectedCases: 42,
        riskLevel: 'High',
        firstReported: '2024-07-18T10:00:00Z',
    },
    {
        id: 'outbreak_02',
        disease: 'Rice Blast',
        crop: 'Rice',
        location: 'Guntur, Andhra Pradesh',
        latitude: 16.3067,
        longitude: 80.4365,
        detectedCases: 25,
        riskLevel: 'Medium',
        firstReported: '2024-07-20T14:00:00Z',
    },
    {
        id: 'outbreak_03',
        disease: 'Maize Common Rust',
        crop: 'Maize',
        location: 'Nashik, Maharashtra',
        latitude: 19.9975,
        longitude: 73.7898,
        detectedCases: 15,
        riskLevel: 'Low',
        firstReported: '2024-07-21T09:00:00Z',
    },
    {
        id: 'outbreak_04',
        disease: 'Tomato Late Blight',
        crop: 'Tomato',
        location: 'Solan, Himachal Pradesh',
        latitude: 30.9083,
        longitude: 77.0996,
        detectedCases: 88,
        riskLevel: 'High',
        firstReported: '2024-07-15T11:30:00Z',
    }
];

export const mockProducts: StoreProduct[] = [
  {
    id: 'prod_001',
    name: 'Neem Oil Concentrate',
    description: 'A natural, organic fungicide and pesticide effective against blights and rusts. Safe for all crops.',
    price: 450,
    currency: 'INR',
    image: getImage('product_neem_oil'),
    imageHint: getImageHint('product_neem_oil'),
    type: 'Organic Fungicide',
    isGovtApproved: true,
  },
  {
    id: 'prod_002',
    name: 'Trichoderma Viride Bio Fungicide',
    description: 'A powerful bio-fungicide that protects crops from soil-borne diseases. Enhances root growth.',
    price: 750,
    currency: 'INR',
    image: getImage('product_trichoderma'),
    imageHint: getImageHint('product_trichoderma'),
    type: 'Organic Fungicide',
    isGovtApproved: true,
  },
  {
    id: 'prod_003',
    name: 'Mancozeb 75% WP',
    description: 'A widely-used contact fungicide for controlling a broad spectrum of diseases in potato and tomato.',
    price: 600,
    currency: 'INR',
    image: getImage('product_mancozeb'),
    imageHint: getImageHint('product_mancozeb'),
    type: 'Chemical Fungicide',
    isGovtApproved: true,
    toxicity: 'Medium',
  },
  {
    id: 'prod_004',
    name: 'Copper Oxychloride',
    description: 'A protective fungicide used to control late blight in potatoes and tomatoes. Govt approved.',
    price: 550,
    currency: 'INR',
    image: getImage('product_copper_oxychloride'),
    imageHint: getImageHint('product_copper_oxychloride'),
    type: 'Chemical Fungicide',
    isGovtApproved: true,
    toxicity: 'Low',
  },
  {
    id: 'prod_005',
    name: 'Beauveria Bassiana Bio-insecticide',
    description: 'An eco-friendly bio-insecticide for managing a wide range of pests. Safe for beneficial insects.',
    price: 800,
    currency: 'INR',
    image: getImage('product_beauveria'),
    imageHint: getImageHint('product_beauveria'),
    type: 'Organic Insecticide',
    isGovtApproved: true,
  },
  {
    id: 'prod_006',
    name: 'Seaweed Extract Bio-stimulant',
    description: 'Promotes root growth and improves nutrient uptake, making plants healthier and more resilient.',
    price: 950,
    currency: 'INR',
    image: getImage('product_seaweed_extract'),
    imageHint: getImageHint('product_seaweed_extract'),
    type: 'Bio-stimulant',
    isGovtApproved: true,
  },
  {
    id: 'prod_007',
    name: 'Verticillium Lecanii',
    description: 'An effective organic insecticide for controlling sucking pests like aphids, jassids, and whiteflies.',
    price: 850,
    currency: 'INR',
    image: getImage('product_verticillium'),
    imageHint: getImageHint('product_verticillium'),
    type: 'Organic Insecticide',
    isGovtApproved: true,
  }
];

export const mockStoreLocations: StoreLocation[] = [
  // Hyderabad and surrounding areas
  {
    id: 'store_hyd_01',
    name: 'Shamshabad Agro Agency',
    address: 'RGI Airport Road, Shamshabad, Hyderabad',
    latitude: 17.2402,
    longitude: 78.4304,
  },
  {
    id: 'store_hyd_02',
    name: 'Ghatkesar Farmers Cooperative',
    address: 'Near ORR, Ghatkesar, Hyderabad',
    latitude: 17.4249,
    longitude: 78.6833,
  },
  {
    id: 'store_hyd_03',
    name: 'Medchal Rythu Seva Kendram',
    address: 'Main Road, Medchal, Telangana',
    latitude: 17.6338,
    longitude: 78.4833,
  },
  {
    id: 'store_hyd_04',
    name: 'Siddipet Agri Supplies',
    address: 'Bus Stand Road, Siddipet, Telangana',
    latitude: 18.1030,
    longitude: 78.8524,
  },
  {
    id: 'store_hyd_05',
    name: 'Secunderabad Pesticides',
    address: 'Market Street, Secunderabad, Hyderabad',
    latitude: 17.4399,
    longitude: 78.4983,
  },
  // Rest of India
  {
    id: 'store_haryana_01',
    name: 'Kisan Seva Kendra',
    address: '123, Main Market, Karnal, Haryana',
    latitude: 29.6857,
    longitude: 76.9905,
  },
  {
    id: 'store_ap_01',
    name: 'Agri Junction',
    address: '45, Ring Road, Guntur, Andhra Pradesh',
    latitude: 16.3067,
    longitude: 80.4365,
  },
  {
    id: 'store_mh_01',
    name: 'Farm Essentials',
    address: '78, Mumbai-Agra Highway, Nashik, Maharashtra',
    latitude: 20.00,
    longitude: 73.78,
  },
  {
    id: 'store_hp_01',
    name: 'Himachal Agro Solutions',
    address: '9, Mall Road, Solan, Himachal Pradesh',
    latitude: 30.9083,
    longitude: 77.0996,
  },
  {
    id: 'store_mh_02',
    name: 'Deccan Farm Supplies',
    address: '56, Pune-Bangalore Highway, Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    id: 'store_punjab_01',
    name: 'Punjab Agro-Tech',
    address: 'Ferozepur Road, Ludhiana, Punjab',
    latitude: 30.9010,
    longitude: 75.8573,
  },
  {
    id: 'store_up_01',
    name: 'Ganga Agro Inputs',
    address: 'GT Road, Kanpur, Uttar Pradesh',
    latitude: 26.4499,
    longitude: 80.3319,
  },
  {
    id: 'store_mp_01',
    name: 'Narmada Kisan Kendra',
    address: 'Hoshangabad Road, Bhopal, Madhya Pradesh',
    latitude: 23.2599,
    longitude: 77.4126,
  },
  {
    id: 'store_ka_01',
    name: 'Cauvery Agri Center',
    address: 'Ring Road, Mysore, Karnataka',
    latitude: 12.2958,
    longitude: 76.6394,
  },
  {
    id: 'store_odisha_01',
    name: 'East Coast Farm Needs',
    address: 'Cuttack Road, Bhubaneswar, Odisha',
    latitude: 20.2961,
    longitude: 85.8245,
  }
];
